// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2VzdpVnwLIxz75BymZUt3-631xdvzZE',
    appId: '1:377596281343:web:0245690257ea3b3fdee7ca',
    messagingSenderId: '377596281343',
    projectId: 'controle-financeiro-flut-8aa38',
    authDomain: 'controle-financeiro-flut-8aa38.firebaseapp.com',
    storageBucket: 'controle-financeiro-flut-8aa38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQefTymwGN12jkyVwqz9Px-M4pOqy5JzU',
    appId: '1:377596281343:android:956ab9b07c96ce50dee7ca',
    messagingSenderId: '377596281343',
    projectId: 'controle-financeiro-flut-8aa38',
    storageBucket: 'controle-financeiro-flut-8aa38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTDdZGtFhswfZzgp32pUdkoou5OzwqeVg',
    appId: '1:377596281343:ios:3d8f870343454ab6dee7ca',
    messagingSenderId: '377596281343',
    projectId: 'controle-financeiro-flut-8aa38',
    storageBucket: 'controle-financeiro-flut-8aa38.firebasestorage.app',
    iosBundleId: 'com.example.controleFinanceiroFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTDdZGtFhswfZzgp32pUdkoou5OzwqeVg',
    appId: '1:377596281343:ios:3d8f870343454ab6dee7ca',
    messagingSenderId: '377596281343',
    projectId: 'controle-financeiro-flut-8aa38',
    storageBucket: 'controle-financeiro-flut-8aa38.firebasestorage.app',
    iosBundleId: 'com.example.controleFinanceiroFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI2VzdpVnwLIxz75BymZUt3-631xdvzZE',
    appId: '1:377596281343:web:f6c0937bb3f9a7ccdee7ca',
    messagingSenderId: '377596281343',
    projectId: 'controle-financeiro-flut-8aa38',
    authDomain: 'controle-financeiro-flut-8aa38.firebaseapp.com',
    storageBucket: 'controle-financeiro-flut-8aa38.firebasestorage.app',
  );
}
